<?php /** @var \Snowdog\Menu\Block\NodeType\Category $block */ ?>
<?php
$nodeId = $block->getId();
$class = $block->getMenuClass();
$categoryUrl = $block->getCategoryUrl($nodeId);
$categoryUrl = $categoryUrl ?: '#';
$dataAttribute = '';
$level = $block->getLevel();
$categoryNodeImage = $this->helper(Pinpoint\Snowdog\Helper\Image::class)->getImageUrl($block->getNodeImage());

if ($block->getIsViewAllLink()) {
    $title = __('');
    $classLink = $class . '__inner-link';
} else {
    $classLink = $block->getIsRoot() ? $class . '__link' : $class . '__inner-link';
    $title = $block->getTitle();

    if ($nodeId) {
        $dataAttribute = ' data-menu="menu-' . $nodeId . '"';
    }

    if ($block->isCurrentCategory($nodeId)) {
        $classLink .= ' current';
    }
}
?>

<a
<?php if ($block->getIsParent()): ?>
  id="parent"
<?php endif ?>
href="<?= $categoryUrl ?>"
class="<?= $classLink ?>"
<?= $dataAttribute ?>
>
<?php if($categoryNodeImage) : ?>
  <div class="menu-item__icon">
    <img src="<?= $categoryNodeImage; ?>" />
  </div>
<?php endif; ?>
<span>
  <?= $title ?>
  <?php if ($block->getIsParent() && !$block->getIsViewAllLink()): ?>
    <span title="view more" class="<?= $class ?>__icon">

    </span>
  <?php endif ?>
</span>
</a>
